#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/**
 * @ac: number of items in av
 * @av: NULL terminated array of strings
 */

int main(int ac, char **av)
{
	char *token;
	char *line = NULL;
	size_t len = 0;

	printf("$ ");
	getline(&line, &len, stdin);

	line[strcspn(line, "\n")] = '\0'; //strips newline generated by getline

	token = strtok(line, ",");

	while (token != NULL)
	{
		printf("%s\n", token);
		token = strtok(NULL, ",");
	}

	free(line);
	return(0);
}
